resources:
  - name: x86_64_Ubuntu_14_04_prep_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/x86_64.Ubuntu_14.04.prep
      branch: master

  - name: u14_dh_cli
    type: cliConfig
    integration: ric03uec-dockerhub

  - name: u14_bits_access_cli
    type: cliConfig
    integration: aws_bits_access
    pointer:
      region: us-east-1

  - name: u14_reqExec_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqExec
      branch: master

  - name: u14_execTemplates_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/execTemplates
      branch: master

  - name: u14_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14
      branch: master

  - name: u14_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14"
    seed:
      versionName: master

  - name: u14all_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14all
      branch: master

  - name: u14all_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14all"
    seed:
      versionName: master

  - name: u14nodall_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14nodall
      branch: master

  - name: u14nodall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14nodall"
    seed:
      versionName: master

  - name: u14pytall_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14pytall
      branch: master

  - name: u14pytall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14pytall"
    seed:
      versionName: master

  - name: u14cloall_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14cloall
      branch: master

  - name: u14cloall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14cloall"
    seed:
      versionName: master

  - name: u14golall_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14golall
      branch: master

  - name: u14golall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14golall"
    seed:
      versionName: master

  - name: u14javall_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14javall
      branch: master

  - name: u14javall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14javall"
    seed:
      versionName: master

  - name: u14scaall_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14scaall
      branch: master

  - name: u14scaall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14scaall"
    seed:
      versionName: master

  - name: u14ruball_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14ruball
      branch: master

  - name: u14ruball_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14ruball"
    seed:
      versionName: master

  - name: u14phpall_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14phpall
      branch: master

  - name: u14phpall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14phpall"
    seed:
      versionName: master

  - name: u14cppall_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/u14cppall
      branch: master

  - name: u14cppall_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/u14cppall"
    seed:
      versionName: master

  - name: microbase_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/microbase
      branch: master

  - name: microbase_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/microbase"
    seed:
      versionName: master

  - name: admiral_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/admiral
      branch: master

  - name: admiral_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/admiral"
    seed:
      versionName: master

  - name: nexec_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/nexec
      branch: master

  - name: nexec_img
    type: image
    integration: ecr_bits_push
    pointer:
      sourceName: "374168611083.dkr.ecr.us-east-1.amazonaws.com/nexec"
    seed:
      versionName: master

  - name: api_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/api
      branch: master

  - name: api_img
    type: image
    integration: ecr_bits_push
    pointer:
      sourceName: "374168611083.dkr.ecr.us-east-1.amazonaws.com/api"
    seed:
      versionName: master

  - name: www_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/www
      branch: master

  - name: www_img
    type: image
    integration: ecr_bits_push
    pointer:
      sourceName: "374168611083.dkr.ecr.us-east-1.amazonaws.com/www"
    seed:
      versionName: master

  - name: mktg_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/mktg
      branch: master

  - name: mktg_img
    type: image
    integration: ecr_bits_push
    pointer:
      sourceName: "374168611083.dkr.ecr.us-east-1.amazonaws.com/mktg"
    seed:
      versionName: master

  - name: genexec_img
    type: image
    integration: ecr_bits_push
    pointer:
      sourceName: "374168611083.dkr.ecr.us-east-1.amazonaws.com/genexec"
    seed:
      versionName: master

  - name: micro_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/micro
      branch: master

  - name: micro_img
    type: image
    integration: ecr_bits_push
    pointer:
      sourceName: "374168611083.dkr.ecr.us-east-1.amazonaws.com/micro"
    seed:
      versionName: master

jobs:
  - name: x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14 x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14_img

  - name: all_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14_img
      - IN: u14all_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14all all_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14all_img

  - name: nod_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14all_img
      - IN: u14nodall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14nodall nod_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14nodall_img

  - name: pyt_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14all_img
      - IN: u14pytall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14pytall pyt_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14pytall_img

  - name: clo_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14all_img
      - IN: u14cloall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14cloall clo_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14cloall_img

  - name: gol_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14all_img
      - IN: u14golall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14golall gol_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14golall_img

  - name: jav_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14all_img
      - IN: u14javall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14javall jav_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14javall_img

  - name: sca_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14javall_img
      - IN: u14scaall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14scaall sca_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14scaall_img

  - name: rub_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14all_img
      - IN: u14ruball_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14ruball rub_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14ruball_img

  - name: php_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14all_img
      - IN: u14phpall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14phpall php_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14phpall_img

  - name: cpp_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14all_img
      - IN: u14cppall_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh u14cppall cpp_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: u14cppall_img

  - name: microbase_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_dh_cli
        switch: off
      - IN: u14_img
      - IN: microbase_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh microbase microbase_x86_64_Ubuntu_14_04_prep
            - popd
      - OUT: microbase_img

  - name: admiral_x86_64_Ubuntu_14_04_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_bits_access_cli
        switch: off
        scopes:
          - ecr
      - IN: microbase_img
      - IN: admiral_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildImage.sh admiral admiral_x86_64_Ubuntu_14_04_prep 374168611083.dkr.ecr.us-east-1.amazonaws.com
            - popd
      - OUT: admiral_img

  # TODO: move this job to x86_64 Ubuntu 14.04
  - name: reqExec_x86_64_Ubuntu_14_04_pack
    type: runSh
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_bits_access_cli
        switch: off
      - IN: u14_reqExec_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./buildAndPushReqExecArtifacts.sh u14_reqExec_repo
            - popd

  - name: ecr_svcs_x86_64_Ubuntu_14_04_prep
    type: runSh
    steps:
      - IN: x86_64_Ubuntu_14_04_prep_repo
        switch: off
      - IN: u14_bits_access_cli
        switch: off
        scopes:
          - ecr
      - IN: microbase_img
        switch: off
      - IN: mktg_repo
      - IN: nexec_repo
      - IN: api_repo
      - IN: www_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_Ubuntu_14_04_prep_repo")
            - ./genBuildImage.sh
            - popd
      - OUT: mktg_img
      - OUT: nexec_img
      - OUT: api_img
      - OUT: www_img

  - name: micro_x86_64_Ubuntu_14_04_prep
    type: runSh
    steps:
      - IN: micro_repo
      - IN: u14_execTemplates_repo
      - IN: microbase_img
      - IN: u14_bits_access_cli
        scopes:
          - ecr
      - IN: u14_dh_cli
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "micro_repo")
            - ./build.sh
            - popd
      - OUT: micro_img
      - OUT: genexec_img
